networks:
  vladislavnet:
    driver: bridge
  traefik_external:
    external: true

services:
  app:
    env_file:
      - .env
    build: docker/php/cli
    volumes:
      - ./:/app
    networks:
      - vladislavnet
    depends_on:
      - db
    working_dir: /app
    tty: true


  php-fpm:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    expose:
      - 9000
    networks:
      traefik_external:
      vladislavnet:
        aliases:
          - php-fpm
    depends_on:
      - db
    volumes:
      - ./:/app

  nginx:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "${NGINX_PUBLIC_PORT}:${NGINX_INTERNAL_PORT}"
    volumes:
      - ./:/app

    depends_on:
      - php-fpm
    networks:
      traefik_external:
      vladislavnet:
        aliases:
          - nginx
          - ${DOMAIN_NAME}

    restart: on-failure
    tty: false


  composer_installation:
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs
    depends_on:
      - app
      - db
      - php-fpm
      - nginx
  db:
    env_file:
      - .env
    image: mysql:latest
    networks:
      vladislavnet:
        aliases:
          - db
          - mysql
    ports:
      - "${MYSQL_PUBLIC_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - ./docker/var/lib/mysql:/var/lib/mysql
      - ./docker/var/log/mysql:/var/log/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d


  migration:
    env_file:
      - .env
    build:
      dockerfile: docker/migration/Dockerfile
    volumes:
      - ./:/app
    networks:
      vladislavnet:
        aliases:
          - db
          - mysql
    depends_on:
      - db
      - app
      - php-fpm
      - nginx
    restart: on-failure
