services:
  nginx:
    image: nginx:1.23-alpine
    volumes:
      - .:/var/www/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./.storage/nginx/logs:/var/log/nginx
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      FASTCGI_PASS: ${FASTCGI_PASS}
    networks:
      - vladislav_network
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: ./docker/php
      target: ${YII_ENV}
      args:
        PHP_IMAGE_TAG: 8.2-fpm
    volumes:
      - .:/var/www/app
    env_file:
      - .env
    networks:
      - vladislav_network
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
    user: ${UID}:${GID}
    restart: unless-stopped

  composer_installation:
    image: composer
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    command: composer install
  redis:
    image: redis:6.2
    volumes:
      - ./.storage/redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - vladislav_network
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.storage/mysql:/var/lib/mysql
    networks:
      - vladislav_network
    restart: unless-stopped
  supervisor:
    build:
      target: base
      context: .
      dockerfile: ./docker/supervisor/Dockerfile
      args:
        PHP_IMAGE_TAG: 8.2-cli
    volumes:
      - .:/var/www/app
      - ./docker/supervisor/conf.d:/etc/supervisor/conf.d
      - ./.storage/supervisor:/var/log/app
      - ./.storage/supervisor:/var/log/supervisor
    env_file:
      - .env
    depends_on:
      php:
        condition: service_started
    networks:
      - vladislav_network
    restart: unless-stopped

networks:
  vladislav_network:
    name: ${NETWORK_NAME}
